name: indextts2
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - git  # needed to use LFS
  - git-lfs  # Git Large File Storage
  - pip
  - numpy=1.26.2
  - pandas=2.3.2
  - numba=0.58.1
  - matplotlib=3.8.2
  - librosa=0.10.2.post1
  - ffmpeg
  - cython=3.0.7
  - accelerate=1.8.1
  - tqdm
  - json5=0.10.0

  - pip:
      - torch==2.8.* --extra-index-url https://download.pytorch.org/whl/cu128
      - torchaudio==2.8.* --extra-index-url https://download.pytorch.org/whl/cu128
      - wetext>=0.0.9; platform_system != "Linux"

      # Linux
      - WeTextProcessing; platform_system == "Linux"
      - accelerate==1.8.1
      - cn2an==0.5.22
      - cython==3.0.7
      - descript-audiotools==0.7.2
      - einops>=0.8.1
      - fastapi==0.121.2
      - ffmpeg-python==0.2.0
      - g2p-en==2.1.0
      - jieba==0.42.1
      - json5==0.10.0
      - keras==2.9.0
      - librosa==0.10.2.post1
      - matplotlib==3.8.2
      - minio==7.2.20
      - modelscope==1.27.0
      - munch==4.0.0
      - numba==0.58.1
      - numpy==1.26.2
      - omegaconf>=2.3.0
      - openai==1.109.1
      - opencv-python==4.9.0.80
      - pandas==2.3.2
      - python-multipart==0.0.20
      - safetensors==0.5.2
      - sentencepiece>=0.2.1
      - tensorboard==2.9.1
      - textstat>=0.7.10
      - tokenizers==0.21.0
      - tqdm>=4.67.1
      - transformers==4.52.1
      - uvicorn==0.38.0
      - wetext>=0.0.9
      - huggingface-hub[cli,hf_xet]
      - modelscope
      - python-dotenv


